
# Don't print a new line at the start of the prompt
add_newline = false

format = """
SH_DIR=${directory}
SH_G_BRANCH=${git_branch}
SH_G_COMMIT=${git_commit}
SH_G_STATE=${git_state}
SH_G_STATUS=${git_status}
SH_CMD_DURATION=${cmd_duration}"""

command_timeout = 2500

[directory]
format = '[($read_only)]($read_only_style)'
#format = '[($read_only)]($read_only_style)[$path]($style)'
truncate_to_repo = true
truncation_length = 0
repo_root_format = "[$repo_root]($style)"
read_only	= " "
truncation_symbol = "…/"
repo_root_style = "none"
style = "none"
read_only_style	= "none"

[git_branch]
always_show_remote = false  #Shows the remote tracking branch name, even if it is equal to the local branch name. default false
format = "[ ($symbol$branch)(,${remote_name}/${remote_branch})]($style)"
symbol = ""
style	= "none"
truncation_symbol = "…"
only_attached =	false #Only show the branch name when not in a detached HEAD state. default false
disabled = false

[git_commit]
format = "[( $tag)]($style)"  #$hash
commit_hash_length = 7
only_detached	= false  #Only show git commit hash when in detached HEAD state
tag_disabled = false
tag_symbol = ' '  # 識
disabled = false
style	= "none"

[git_state]
rebase = "REBASING"
merge	= "MERGING"
revert = "REVERTING"
cherry_pick	= "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"	 #A format string displayed when an apply-mailbox (git am) is in progress.
am_or_rebase = "AM/REBASE"	#A format string displayed when an ambiguous apply-mailbox or rebase is in progress.
style	= "none"
format = '[ $state(,$progress_current/$progress_total)]($style)'
disabled = false

[git_status] 
format = '( $ahead_behind$conflicted$staged$deleted$modified$renamed$untracked$stashed)' #       ❲❳ 
conflicted = "[!${count}](none)"
ahead = "[${count}](none)"
behind = "[${count}](none)"
diverged = "[${ahead_count}${behind_count}](none)"
untracked = "[?${count}](none)"
stashed = '[s${count}](none)'
modified = "[~${count}](none)"
staged = "[+${count}](none)"
renamed = "[>${count}](none)"
deleted = "[-${count}](none)"
disabled = false

[cmd_duration]
min_time = 500
style	= "none"
format = "[( $duration)]($style)"
show_milliseconds = true
#show_notifications = true
#min_time_to_notify = 2000
