#include "farversion.hpp"

#define PLUGIN_DESC L"Show git info at command propmt"
#define PLUGIN_NAME L"GitInfo"
#define PLUGIN_FILENAME L"gitbranch.dll"
#define PLUGIN_AUTHOR L"V.Matyukha"
#define PLUGIN_COPYRIGHT_INITIAL L"© V.Matyukha, 2022-2022."
#define PLUGIN_COPYRIGHT_CURRENT_FROM 2000

#define PLUGIN_VERSION MAKEFARVERSION(PLUGIN_MAJOR,PLUGIN_MINOR,PLUGIN_BUILD,PLUGIN_REVISION,VS_RELEASE)

